services:
  pvz:
    build: ./
    command: ./wait-for-postgres.sh db ./pvz
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - MODE=prod
      - DB_PASSWORD=qwerty
      - ENV=prod

  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/val/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    # volumes:
    # - pgdata
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
  
  redis:
    image: redis:latest
    restart: unless-stopeed
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  pgdata:
  redis_data:
