// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/order/order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ExpireAfter   int32                  `protobuf:"varint,3,opt,name=expire_after,json=expireAfter,proto3" json:"expire_after,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Packing       string                 `protobuf:"bytes,6,opt,name=packing,proto3" json:"packing,omitempty"`
	Extra         bool                   `protobuf:"varint,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_api_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AddOrderRequest) GetExpireAfter() int32 {
	if x != nil {
		return x.ExpireAfter
	}
	return 0
}

func (x *AddOrderRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AddOrderRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddOrderRequest) GetPacking() string {
	if x != nil {
		return x.Packing
	}
	return ""
}

func (x *AddOrderRequest) GetExtra() bool {
	if x != nil {
		return x.Extra
	}
	return false
}

type AddOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderResponse) Reset() {
	*x = AddOrderResponse{}
	mi := &file_api_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderResponse) ProtoMessage() {}

func (x *AddOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderResponse.ProtoReflect.Descriptor instead.
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrderRequest) Reset() {
	*x = RemoveOrderRequest{}
	mi := &file_api_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrderRequest) ProtoMessage() {}

func (x *RemoveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrderRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RemoveOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrderResponse) Reset() {
	*x = RemoveOrderResponse{}
	mi := &file_api_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrderResponse) ProtoMessage() {}

func (x *RemoveOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrderResponse.ProtoReflect.Descriptor instead.
func (*RemoveOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_order_order_proto protoreflect.FileDescriptor

const file_api_order_order_proto_rawDesc = "" +
	"\n" +
	"\x15api/order/order.proto\x12\x05order\"\xc6\x01\n" +
	"\x0fAddOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12!\n" +
	"\fexpire_after\x18\x03 \x01(\x05R\vexpireAfter\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x18\n" +
	"\apacking\x18\x06 \x01(\tR\apacking\x12\x14\n" +
	"\x05extra\x18\a \x01(\bR\x05extra\",\n" +
	"\x10AddOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x12RemoveOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"/\n" +
	"\x13RemoveOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x87\x01\n" +
	"\x05Order\x12;\n" +
	"\x06Create\x12\x16.order.AddOrderRequest\x1a\x17.order.AddOrderResponse\"\x00\x12A\n" +
	"\x06Remove\x12\x19.order.RemoveOrderRequest\x1a\x1a.order.RemoveOrderResponse\"\x00B\x06Z\x04/apib\x06proto3"

var (
	file_api_order_order_proto_rawDescOnce sync.Once
	file_api_order_order_proto_rawDescData []byte
)

func file_api_order_order_proto_rawDescGZIP() []byte {
	file_api_order_order_proto_rawDescOnce.Do(func() {
		file_api_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_order_proto_rawDesc), len(file_api_order_order_proto_rawDesc)))
	})
	return file_api_order_order_proto_rawDescData
}

var file_api_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_order_order_proto_goTypes = []any{
	(*AddOrderRequest)(nil),     // 0: order.AddOrderRequest
	(*AddOrderResponse)(nil),    // 1: order.AddOrderResponse
	(*RemoveOrderRequest)(nil),  // 2: order.RemoveOrderRequest
	(*RemoveOrderResponse)(nil), // 3: order.RemoveOrderResponse
}
var file_api_order_order_proto_depIdxs = []int32{
	0, // 0: order.Order.Create:input_type -> order.AddOrderRequest
	2, // 1: order.Order.Remove:input_type -> order.RemoveOrderRequest
	1, // 2: order.Order.Create:output_type -> order.AddOrderResponse
	3, // 3: order.Order.Remove:output_type -> order.RemoveOrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_order_order_proto_init() }
func file_api_order_order_proto_init() {
	if File_api_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_order_proto_rawDesc), len(file_api_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_order_proto_goTypes,
		DependencyIndexes: file_api_order_order_proto_depIdxs,
		MessageInfos:      file_api_order_order_proto_msgTypes,
	}.Build()
	File_api_order_order_proto = out.File
	file_api_order_order_proto_goTypes = nil
	file_api_order_order_proto_depIdxs = nil
}
