// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/order_info/order_info.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpireAfter   int32                  `protobuf:"varint,3,opt,name=expire_after,json=expireAfter,proto3" json:"expire_after,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Packing       string                 `protobuf:"bytes,6,opt,name=packing,proto3" json:"packing,omitempty"`
	Extra         bool                   `protobuf:"varint,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_api_order_info_order_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_info_order_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_api_order_info_order_info_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfo) GetExpireAfter() int32 {
	if x != nil {
		return x.ExpireAfter
	}
	return 0
}

func (x *OrderInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *OrderInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetPacking() string {
	if x != nil {
		return x.Packing
	}
	return ""
}

func (x *OrderInfo) GetExtra() bool {
	if x != nil {
		return x.Extra
	}
	return false
}

func (x *OrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfo) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *OrderInfo) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *OrderInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_order_info_order_info_proto protoreflect.FileDescriptor

const file_api_order_info_order_info_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/order_info/order_info.proto\x12\n" +
	"order_info\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12!\n" +
	"\fexpire_after\x18\x03 \x01(\x05R\vexpireAfter\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x18\n" +
	"\apacking\x18\x06 \x01(\tR\apacking\x12\x14\n" +
	"\x05extra\x18\a \x01(\bR\x05extra\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x127\n" +
	"\texpire_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x127\n" +
	"\tupdate_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06Z\x04/apib\x06proto3"

var (
	file_api_order_info_order_info_proto_rawDescOnce sync.Once
	file_api_order_info_order_info_proto_rawDescData []byte
)

func file_api_order_info_order_info_proto_rawDescGZIP() []byte {
	file_api_order_info_order_info_proto_rawDescOnce.Do(func() {
		file_api_order_info_order_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_info_order_info_proto_rawDesc), len(file_api_order_info_order_info_proto_rawDesc)))
	})
	return file_api_order_info_order_info_proto_rawDescData
}

var file_api_order_info_order_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_order_info_order_info_proto_goTypes = []any{
	(*OrderInfo)(nil),             // 0: order_info.OrderInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_order_info_order_info_proto_depIdxs = []int32{
	1, // 0: order_info.OrderInfo.expire_at:type_name -> google.protobuf.Timestamp
	1, // 1: order_info.OrderInfo.update_at:type_name -> google.protobuf.Timestamp
	1, // 2: order_info.OrderInfo.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_order_info_order_info_proto_init() }
func file_api_order_info_order_info_proto_init() {
	if File_api_order_info_order_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_info_order_info_proto_rawDesc), len(file_api_order_info_order_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_order_info_order_info_proto_goTypes,
		DependencyIndexes: file_api_order_info_order_info_proto_depIdxs,
		MessageInfos:      file_api_order_info_order_info_proto_msgTypes,
	}.Build()
	File_api_order_info_order_info_proto = out.File
	file_api_order_info_order_info_proto_goTypes = nil
	file_api_order_info_order_info_proto_depIdxs = nil
}
