// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/pvz/pvz.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefundListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Pattern       map[string]string      `protobuf:"bytes,4,rep,name=pattern,proto3" json:"pattern,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundListRequest) Reset() {
	*x = RefundListRequest{}
	mi := &file_api_pvz_pvz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundListRequest) ProtoMessage() {}

func (x *RefundListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_pvz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundListRequest.ProtoReflect.Descriptor instead.
func (*RefundListRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_pvz_proto_rawDescGZIP(), []int{0}
}

func (x *RefundListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RefundListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RefundListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *RefundListRequest) GetPattern() map[string]string {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type RefundListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundListResponse) Reset() {
	*x = RefundListResponse{}
	mi := &file_api_pvz_pvz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundListResponse) ProtoMessage() {}

func (x *RefundListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_pvz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundListResponse.ProtoReflect.Descriptor instead.
func (*RefundListResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *RefundListResponse) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

type HistoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Pattern       map[string]string      `protobuf:"bytes,4,rep,name=pattern,proto3" json:"pattern,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryListRequest) Reset() {
	*x = HistoryListRequest{}
	mi := &file_api_pvz_pvz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryListRequest) ProtoMessage() {}

func (x *HistoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_pvz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryListRequest.ProtoReflect.Descriptor instead.
func (*HistoryListRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_pvz_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *HistoryListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *HistoryListRequest) GetPattern() map[string]string {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type HistoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryListResponse) Reset() {
	*x = HistoryListResponse{}
	mi := &file_api_pvz_pvz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryListResponse) ProtoMessage() {}

func (x *HistoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_pvz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryListResponse.ProtoReflect.Descriptor instead.
func (*HistoryListResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_pvz_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryListResponse) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_api_pvz_pvz_proto protoreflect.FileDescriptor

const file_api_pvz_pvz_proto_rawDesc = "" +
	"\n" +
	"\x11api/pvz/pvz.proto\x12\x03pvz\x1a\x1fapi/order_info/order_info.proto\"\xd3\x01\n" +
	"\x11RefundListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12=\n" +
	"\apattern\x18\x04 \x03(\v2#.pvz.RefundListRequest.PatternEntryR\apattern\x1a:\n" +
	"\fPatternEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x12RefundListResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.order_info.OrderInfoR\x06orders\"\xd5\x01\n" +
	"\x12HistoryListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12>\n" +
	"\apattern\x18\x04 \x03(\v2$.pvz.HistoryListRequest.PatternEntryR\apattern\x1a:\n" +
	"\fPatternEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x13HistoryListResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.order_info.OrderInfoR\x06orders2\x8a\x01\n" +
	"\x03PVZ\x12?\n" +
	"\n" +
	"RefundList\x12\x16.pvz.RefundListRequest\x1a\x17.pvz.RefundListResponse\"\x00\x12B\n" +
	"\vHistoryList\x12\x17.pvz.HistoryListRequest\x1a\x18.pvz.HistoryListResponse\"\x00B\x06Z\x04/apib\x06proto3"

var (
	file_api_pvz_pvz_proto_rawDescOnce sync.Once
	file_api_pvz_pvz_proto_rawDescData []byte
)

func file_api_pvz_pvz_proto_rawDescGZIP() []byte {
	file_api_pvz_pvz_proto_rawDescOnce.Do(func() {
		file_api_pvz_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pvz_pvz_proto_rawDesc), len(file_api_pvz_pvz_proto_rawDesc)))
	})
	return file_api_pvz_pvz_proto_rawDescData
}

var file_api_pvz_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_pvz_pvz_proto_goTypes = []any{
	(*RefundListRequest)(nil),   // 0: pvz.RefundListRequest
	(*RefundListResponse)(nil),  // 1: pvz.RefundListResponse
	(*HistoryListRequest)(nil),  // 2: pvz.HistoryListRequest
	(*HistoryListResponse)(nil), // 3: pvz.HistoryListResponse
	nil,                         // 4: pvz.RefundListRequest.PatternEntry
	nil,                         // 5: pvz.HistoryListRequest.PatternEntry
	(*OrderInfo)(nil),           // 6: order_info.OrderInfo
}
var file_api_pvz_pvz_proto_depIdxs = []int32{
	4, // 0: pvz.RefundListRequest.pattern:type_name -> pvz.RefundListRequest.PatternEntry
	6, // 1: pvz.RefundListResponse.orders:type_name -> order_info.OrderInfo
	5, // 2: pvz.HistoryListRequest.pattern:type_name -> pvz.HistoryListRequest.PatternEntry
	6, // 3: pvz.HistoryListResponse.orders:type_name -> order_info.OrderInfo
	0, // 4: pvz.PVZ.RefundList:input_type -> pvz.RefundListRequest
	2, // 5: pvz.PVZ.HistoryList:input_type -> pvz.HistoryListRequest
	1, // 6: pvz.PVZ.RefundList:output_type -> pvz.RefundListResponse
	3, // 7: pvz.PVZ.HistoryList:output_type -> pvz.HistoryListResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_pvz_pvz_proto_init() }
func file_api_pvz_pvz_proto_init() {
	if File_api_pvz_pvz_proto != nil {
		return
	}
	file_api_order_info_order_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pvz_pvz_proto_rawDesc), len(file_api_pvz_pvz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pvz_pvz_proto_goTypes,
		DependencyIndexes: file_api_pvz_pvz_proto_depIdxs,
		MessageInfos:      file_api_pvz_pvz_proto_msgTypes,
	}.Build()
	File_api_pvz_pvz_proto = out.File
	file_api_pvz_pvz_proto_goTypes = nil
	file_api_pvz_pvz_proto_depIdxs = nil
}
