// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/user/user.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefundOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       []int32                `protobuf:"varint,2,rep,packed,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderRequest) Reset() {
	*x = RefundOrderRequest{}
	mi := &file_api_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderRequest) ProtoMessage() {}

func (x *RefundOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderRequest.ProtoReflect.Descriptor instead.
func (*RefundOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *RefundOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundOrderRequest) GetOrderId() []int32 {
	if x != nil {
		return x.OrderId
	}
	return nil
}

type RefundOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderResponse) Reset() {
	*x = RefundOrderResponse{}
	mi := &file_api_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderResponse) ProtoMessage() {}

func (x *RefundOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderResponse.ProtoReflect.Descriptor instead.
func (*RefundOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *RefundOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReturnOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       []int32                `protobuf:"varint,2,rep,packed,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnOrderRequest) Reset() {
	*x = ReturnOrderRequest{}
	mi := &file_api_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnOrderRequest) ProtoMessage() {}

func (x *ReturnOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnOrderRequest.ProtoReflect.Descriptor instead.
func (*ReturnOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReturnOrderRequest) GetOrderId() []int32 {
	if x != nil {
		return x.OrderId
	}
	return nil
}

type ReturnOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnOrderResponse) Reset() {
	*x = ReturnOrderResponse{}
	mi := &file_api_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnOrderResponse) ProtoMessage() {}

func (x *ReturnOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnOrderResponse.ProtoReflect.Descriptor instead.
func (*ReturnOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastN         int32                  `protobuf:"varint,2,opt,name=last_n,json=lastN,proto3" json:"last_n,omitempty"`
	Located       bool                   `protobuf:"varint,3,opt,name=located,proto3" json:"located,omitempty"`
	Pattern       map[string]string      `protobuf:"bytes,4,rep,name=pattern,proto3" json:"pattern,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRequest) GetLastN() int32 {
	if x != nil {
		return x.LastN
	}
	return 0
}

func (x *ListRequest) GetLocated() bool {
	if x != nil {
		return x.Located
	}
	return false
}

func (x *ListRequest) GetPattern() map[string]string {
	if x != nil {
		return x.Pattern
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_api_user_user_proto protoreflect.FileDescriptor

const file_api_user_user_proto_rawDesc = "" +
	"\n" +
	"\x13api/user/user.proto\x12\x04user\x1a\x1fapi/order_info/order_info.proto\"H\n" +
	"\x12RefundOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x03(\x05R\aorderId\"/\n" +
	"\x13RefundOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"H\n" +
	"\x12ReturnOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x03(\x05R\aorderId\"/\n" +
	"\x13ReturnOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xcd\x01\n" +
	"\vListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x15\n" +
	"\x06last_n\x18\x02 \x01(\x05R\x05lastN\x12\x18\n" +
	"\alocated\x18\x03 \x01(\bR\alocated\x128\n" +
	"\apattern\x18\x04 \x03(\v2\x1e.user.ListRequest.PatternEntryR\apattern\x1a:\n" +
	"\fPatternEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\fListResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.order_info.OrderInfoR\x06orders2\xb9\x01\n" +
	"\x04User\x12?\n" +
	"\x06Refund\x12\x18.user.RefundOrderRequest\x1a\x19.user.RefundOrderResponse\"\x00\x12?\n" +
	"\x06Return\x12\x18.user.ReturnOrderRequest\x1a\x19.user.ReturnOrderResponse\"\x00\x12/\n" +
	"\x04List\x12\x11.user.ListRequest\x1a\x12.user.ListResponse\"\x00B\x06Z\x04/apib\x06proto3"

var (
	file_api_user_user_proto_rawDescOnce sync.Once
	file_api_user_user_proto_rawDescData []byte
)

func file_api_user_user_proto_rawDescGZIP() []byte {
	file_api_user_user_proto_rawDescOnce.Do(func() {
		file_api_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_user_proto_rawDesc), len(file_api_user_user_proto_rawDesc)))
	})
	return file_api_user_user_proto_rawDescData
}

var file_api_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_user_user_proto_goTypes = []any{
	(*RefundOrderRequest)(nil),  // 0: user.RefundOrderRequest
	(*RefundOrderResponse)(nil), // 1: user.RefundOrderResponse
	(*ReturnOrderRequest)(nil),  // 2: user.ReturnOrderRequest
	(*ReturnOrderResponse)(nil), // 3: user.ReturnOrderResponse
	(*ListRequest)(nil),         // 4: user.ListRequest
	(*ListResponse)(nil),        // 5: user.ListResponse
	nil,                         // 6: user.ListRequest.PatternEntry
	(*OrderInfo)(nil),           // 7: order_info.OrderInfo
}
var file_api_user_user_proto_depIdxs = []int32{
	6, // 0: user.ListRequest.pattern:type_name -> user.ListRequest.PatternEntry
	7, // 1: user.ListResponse.orders:type_name -> order_info.OrderInfo
	0, // 2: user.User.Refund:input_type -> user.RefundOrderRequest
	2, // 3: user.User.Return:input_type -> user.ReturnOrderRequest
	4, // 4: user.User.List:input_type -> user.ListRequest
	1, // 5: user.User.Refund:output_type -> user.RefundOrderResponse
	3, // 6: user.User.Return:output_type -> user.ReturnOrderResponse
	5, // 7: user.User.List:output_type -> user.ListResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_user_user_proto_init() }
func file_api_user_user_proto_init() {
	if File_api_user_user_proto != nil {
		return
	}
	file_api_order_info_order_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_user_proto_rawDesc), len(file_api_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_user_proto_goTypes,
		DependencyIndexes: file_api_user_user_proto_depIdxs,
		MessageInfos:      file_api_user_user_proto_msgTypes,
	}.Build()
	File_api_user_user_proto = out.File
	file_api_user_user_proto_goTypes = nil
	file_api_user_user_proto_depIdxs = nil
}
